In [1]:
import numpy as np
import matplotlib.pyplot as plt
import urllib

In [2]:
url = 'https://courses.engr.illinois.edu/ece498icc/sp2019/lab1_string.php'
values = {'netid':'smeng10', 'name':'Siping Meng'}

data = urllib.parse.urlencode(values)
data = data.encode('ascii') # data should be bytes
req = urllib.request.Request(url, data)
with urllib.request.urlopen(req) as response:
    the_page = response.read()

In [3]:
def findString(text):
    length = 0
    while length < 400:
        yield text[length*498]
        length+=1

In [4]:
"".join(findString(the_page.decode('ascii')))

'"I was born in California."  "Which part?"  "All of me."  Hello Siping Meng! I hope you enjoy the course.                                                                                                                                                                                                                                                                                                       '

In [122]:
#Part II

In [5]:
import numpy as np

In [6]:
arr = np.zeros((9,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
arr[:,1:5] = 1
arr[2:7,(1,4)] = 0
arr

array([[0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.]])

In [8]:
B = np.vstack((np.vstack((np.zeros(6),arr)),np.zeros(6)))
B

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
C = np.arange(1,67).reshape(11,6)
C

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66]])

In [10]:
D = np.multiply(B,C)
D

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  8.,  9., 10., 11.,  0.],
       [ 0., 14., 15., 16., 17.,  0.],
       [ 0.,  0., 21., 22.,  0.,  0.],
       [ 0.,  0., 27., 28.,  0.,  0.],
       [ 0.,  0., 33., 34.,  0.,  0.],
       [ 0.,  0., 39., 40.,  0.,  0.],
       [ 0.,  0., 45., 46.,  0.,  0.],
       [ 0., 50., 51., 52., 53.,  0.],
       [ 0., 56., 57., 58., 59.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
x,y = D.nonzero()
E = D[x,y]
E

array([ 8.,  9., 10., 11., 14., 15., 16., 17., 21., 22., 27., 28., 33.,
       34., 39., 40., 45., 46., 50., 51., 52., 53., 56., 57., 58., 59.])

In [12]:
max, min = E.max(), E.min()
F = (E - min) / (max - min)
F

array([0.        , 0.01960784, 0.03921569, 0.05882353, 0.11764706,
       0.1372549 , 0.15686275, 0.17647059, 0.25490196, 0.2745098 ,
       0.37254902, 0.39215686, 0.49019608, 0.50980392, 0.60784314,
       0.62745098, 0.7254902 , 0.74509804, 0.82352941, 0.84313725,
       0.8627451 , 0.88235294, 0.94117647, 0.96078431, 0.98039216,
       1.        ])

In [13]:
F[np.abs(F-0.25).argmin()]

0.2549019607843137